// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDl6MHqaR8W-n37WfXTm5ivHpNxtUfgqu8',
    appId: '1:323656730456:android:cb34f3364a390fce4dc72d',
    messagingSenderId: '323656730456',
    projectId: 'gongura-griha',
    storageBucket: 'gongura-griha.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDNv5c_u2xxYd61htlFoUUzdStlEkXVlV8',
    appId: '1:323656730456:ios:14dcd3145482aa554dc72d',
    messagingSenderId: '323656730456',
    projectId: 'gongura-griha',
    storageBucket: 'gongura-griha.firebasestorage.app',
    iosBundleId: 'com.gongura.gonguraGriha',
  );

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCtm0OHsGB7eqoNWHsiX6wMde2v9u1l4GA',
    appId: '1:323656730456:web:512d133e135584f04dc72d',
    messagingSenderId: '323656730456',
    projectId: 'gongura-griha',
    authDomain: 'gongura-griha.firebaseapp.com',
    storageBucket: 'gongura-griha.firebasestorage.app',
  );

}